/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.portugol.plugin.maspath.telas;

import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import javax.swing.JLabel;

/**
 *
 * @author Adson
 */
public class conteudoPane extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form conteudoPane
     */
    public conteudoPane(String titulo) {
        initComponents();
        configurarCores();
        labelTitulo.setText(titulo);
    }

    @Override
    public void configurarCores() {
        setBackground(ColorController.FUNDO_MEDIO);
        labelIcone.setForeground(ColorController.COR_LETRA);
        labelTitulo.setForeground(ColorController.COR_LETRA);
    }

    public JLabel getLabelIcone() {
        return labelIcone;
    }

    public void setLabelIcone(JLabel labelIcone) {
        this.labelIcone = labelIcone;
    }

    public JLabel getLabelTitulo() {
        return labelTitulo;
    }

    public void setLabelTitulo(JLabel labelTitulo) {
        this.labelTitulo = labelTitulo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelIcone = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        labelTitulo.setText("TituloConteudo");
        add(labelTitulo);

        labelIcone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        add(labelIcone);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelIcone;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
