/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.portugol.plugin.maspath.telas;

import br.univali.portugol.plugin.maspath.drawer.GraphDrawer;
import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import com.alee.extended.image.DisplayType;
import com.alee.extended.image.WebImage;
import java.awt.Image;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Space Today
 */
public class painelMenuPrincipal extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form painelMenuPrincipal
     */
    
    GraphDrawer drawer = new GraphDrawer();
    
    public painelMenuPrincipal() {
        initComponents();
        configurarCores();
        configuraPainel();
    }
    
    private void configuraPainel()
    {
        setImage(drawer.drawGraph());
    }

    @Override
    public void configurarCores() {
        this.setBackground(ColorController.COR_PRINCIPAL);
        painelUsuário.setBackground(ColorController.COR_DESTAQUE);
        labelPicUsuario.setForeground(ColorController.COR_LETRA);
        labelNomeUsuario.setForeground(ColorController.COR_LETRA);
        if(WeblafUtils.weblafEstaInstalado())
        {
            WeblafUtils.configurarBotao(botaoAjuda, ColorController.FUNDO_ESCURO, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 10, true);
            WeblafUtils.configurarBotao(botaoConfiguracoes, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 10, true);
            WeblafUtils.configurarBotao(botaoLogout, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 10, true);
            WeblafUtils.configurarBotao(botaoPerguntar, ColorController.FUNDO_ESCURO, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 10, true);
            WeblafUtils.configurarBotao(botaoSelecionarConteudo, ColorController.FUNDO_ESCURO, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 10, true);
            WeblafUtils.configurarBotao(botaoVerTrilhas, ColorController.FUNDO_ESCURO, ColorController.COR_LETRA, ColorController.COR_DESTAQUE, ColorController.COR_LETRA, 10, true);
            
        }
    }
    
    private void setImage(Image image){
        SwingUtilities.invokeLater(() -> {            
            painelTrilha.removeAll();
            WebImage webImage = new WebImage(image);
            webImage.setDisplayType(DisplayType.fitComponent);
            painelTrilha.add(webImage);
            painelTrilha.revalidate();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painelMenu = new javax.swing.JPanel();
        botaoVerTrilhas = new com.alee.laf.button.WebButton();
        botaoSelecionarConteudo = new com.alee.laf.button.WebButton();
        botaoPerguntar = new com.alee.laf.button.WebButton();
        botaoAjuda = new com.alee.laf.button.WebButton();
        painelUsuário = new javax.swing.JPanel();
        labelPicUsuario = new javax.swing.JLabel();
        labelNomeUsuario = new javax.swing.JLabel();
        botaoLogout = new com.alee.laf.button.WebButton();
        botaoConfiguracoes = new com.alee.laf.button.WebButton();
        painelTrilha = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(810, 480));
        setPreferredSize(new java.awt.Dimension(810, 480));
        setLayout(new java.awt.GridBagLayout());

        painelMenu.setMinimumSize(new java.awt.Dimension(200, 480));
        painelMenu.setOpaque(false);
        painelMenu.setPreferredSize(new java.awt.Dimension(200, 480));
        painelMenu.setLayout(new java.awt.GridBagLayout());

        botaoVerTrilhas.setText("<html><div style=\"text-align:center\">Ver Trilhas");
        botaoVerTrilhas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoVerTrilhas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoVerTrilhas.setPreferredSize(new java.awt.Dimension(120, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        painelMenu.add(botaoVerTrilhas, gridBagConstraints);

        botaoSelecionarConteudo.setText("<html><div style=\"text-align:center\">Selecionar Conteúdo");
        botaoSelecionarConteudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoSelecionarConteudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSelecionarConteudo.setPreferredSize(new java.awt.Dimension(120, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        painelMenu.add(botaoSelecionarConteudo, gridBagConstraints);

        botaoPerguntar.setText("<html><div style=\"text-align:center\">Pergunte ao Sistema");
        botaoPerguntar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoPerguntar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoPerguntar.setPreferredSize(new java.awt.Dimension(120, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        painelMenu.add(botaoPerguntar, gridBagConstraints);

        botaoAjuda.setText("<html><div style=\"text-align:center\">Ajuda");
        botaoAjuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoAjuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAjuda.setPreferredSize(new java.awt.Dimension(120, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        painelMenu.add(botaoAjuda, gridBagConstraints);

        painelUsuário.setMinimumSize(new java.awt.Dimension(100, 120));
        painelUsuário.setOpaque(false);
        painelUsuário.setPreferredSize(new java.awt.Dimension(100, 120));
        painelUsuário.setLayout(new java.awt.GridBagLayout());

        labelPicUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPicUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userpic100.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        painelUsuário.add(labelPicUsuario, gridBagConstraints);

        labelNomeUsuario.setText("Nome do Usuário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        painelUsuário.add(labelNomeUsuario, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 15, 40);
        painelMenu.add(painelUsuário, gridBagConstraints);

        botaoLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        painelMenu.add(botaoLogout, gridBagConstraints);

        botaoConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gear_in.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        painelMenu.add(botaoConfiguracoes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(painelMenu, gridBagConstraints);

        painelTrilha.setMinimumSize(new java.awt.Dimension(610, 480));
        painelTrilha.setOpaque(false);
        painelTrilha.setPreferredSize(new java.awt.Dimension(610, 480));
        painelTrilha.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(painelTrilha, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton botaoAjuda;
    private com.alee.laf.button.WebButton botaoConfiguracoes;
    private com.alee.laf.button.WebButton botaoLogout;
    private com.alee.laf.button.WebButton botaoPerguntar;
    private com.alee.laf.button.WebButton botaoSelecionarConteudo;
    private com.alee.laf.button.WebButton botaoVerTrilhas;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JLabel labelPicUsuario;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel painelTrilha;
    private javax.swing.JPanel painelUsuário;
    // End of variables declaration//GEN-END:variables
}
