/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.portugol.plugin.maspath.telas;

import br.univali.ps.ui.swing.ColorController;
import br.univali.ps.ui.swing.Themeable;
import br.univali.ps.ui.swing.weblaf.WeblafUtils;
import com.alee.extended.layout.WrapFlowLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.plaf.ComboBoxUI;
import javax.swing.plaf.basic.BasicComboBoxUI;

/**
 *
 * @author Adson
 */
public class SelecaoConteudo extends javax.swing.JPanel implements Themeable{

    /**
     * Creates new form selecaoConteudo
     */
    
    List<conteudoPane> conteudos;
    List<conteudoPane> conteudosRecomendados;
    
    
    public SelecaoConteudo() {
        initComponents();
        configurarCores();
        conteudos = new ArrayList<>();
        conteudosRecomendados = new ArrayList<>();
        selectablePane.setLayout(new WrapFlowLayout(false, 5, 5));
        setComboBoxes();
        setConteudos();
        adicionarConteudos();
    }
    
    @Override
    public void configurarCores() {
        this.setBackground(ColorController.FUNDO_MEDIO);
        selectablePane.setBackground(ColorController.FUNDO_CLARO);
        recommendContentPane.setBackground(ColorController.FUNDO_CLARO);
        tipoLabel.setForeground(ColorController.COR_LETRA);
        temaLabel.setForeground(ColorController.COR_LETRA);
        dificuldadeLabel.setForeground(ColorController.COR_LETRA);
        nivellLabel.setForeground(ColorController.COR_LETRA);
        recommendTitleLabel.setForeground(ColorController.COR_LETRA);
        choiceLabel.setForeground(ColorController.COR_LETRA);
        if(WeblafUtils.weblafEstaInstalado())
        {
            WeblafUtils.configuraWebLaf(choiceScrollPane);
            WeblafUtils.configuraWebLaf(recommendScrollPane);
        }
        
        
        comboxdificuldade.setExpandedBgColor(ColorController.FUNDO_CLARO);
        comboxdificuldade.setBackground(ColorController.FUNDO_CLARO);
        comboxdificuldade.setForeground(ColorController.COR_LETRA);
        comboxdificuldade.setWebColoredBackground(false);
        
        comboxnivel.setExpandedBgColor(ColorController.FUNDO_CLARO);
        comboxnivel.setBackground(ColorController.FUNDO_CLARO);
        comboxnivel.setForeground(ColorController.COR_LETRA);
        comboxnivel.setWebColoredBackground(false);
        
        comboxtema.setExpandedBgColor(ColorController.FUNDO_CLARO);
        comboxtema.setBackground(ColorController.FUNDO_CLARO);
        comboxtema.setForeground(ColorController.COR_LETRA);
        comboxtema.setWebColoredBackground(false);
        
        comboxtipo.setExpandedBgColor(ColorController.FUNDO_CLARO);
        comboxtipo.setBackground(ColorController.FUNDO_CLARO);
        comboxtipo.setForeground(ColorController.COR_LETRA);
        comboxtipo.setWebColoredBackground(false);
        
        choiceScrollPane.setBorder(null);
        recommendScrollPane.setBorder(null);
    }

    public void setConteudos()
    {
        //conteudos.add(new conteudoPane("Olá Mundo"));
        conteudos.add(new conteudoPane("Operacoes Simples"));
        conteudos.add(new conteudoPane("Prioridades"));
        conteudos.add(new conteudoPane("Altura Média"));
        conteudos.add(new conteudoPane("MiniCalculadora"));
        conteudos.add(new conteudoPane("Factorial"));
        
        conteudosRecomendados.add(new conteudoPane("Velocidade Média"));
        conteudosRecomendados.add(new conteudoPane("Gravidade"));
    }
    
    public void adicionarConteudos()
    {
        for (conteudoPane conteudo : conteudos) {
            selectablePane.add(conteudo);
        }
        
        for (conteudoPane conteudo : conteudosRecomendados) {
            recommendContentPane.add(conteudo);
        }
        //setPreferredSize(new Dimension(506, 356));
    }
    
    public void setComboBoxes()
    {
        comboxdificuldade.addItem("Fácil");
        comboxdificuldade.addItem("Médio");
        comboxdificuldade.addItem("Dificil");
        
        comboxnivel.addItem("1");
        comboxnivel.addItem("2");
        comboxnivel.addItem("3");
        comboxnivel.addItem("4");
        
        comboxtipo.addItem("Exercício");
        comboxtipo.addItem("Material");
        comboxtipo.addItem("Video");
        
        comboxtema.addItem("Matemática");
        comboxtema.addItem("Física");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recommedPanel = new javax.swing.JPanel();
        recommendTitlePanel = new javax.swing.JPanel();
        recommendTitleLabel = new javax.swing.JLabel();
        recommendScrollPane = new javax.swing.JScrollPane();
        recommendContentPane = new javax.swing.JPanel();
        choicePane = new javax.swing.JPanel();
        choiceTitlePane = new javax.swing.JPanel();
        choiceLabel = new javax.swing.JLabel();
        choiceScrollPane = new javax.swing.JScrollPane();
        selectablePane = new javax.swing.JPanel();
        paneFilter = new javax.swing.JPanel();
        tipoLabel = new javax.swing.JLabel();
        comboxtipo = new com.alee.laf.combobox.WebComboBox();
        nivellLabel = new javax.swing.JLabel();
        comboxnivel = new com.alee.laf.combobox.WebComboBox();
        dificuldadeLabel = new javax.swing.JLabel();
        comboxdificuldade = new com.alee.laf.combobox.WebComboBox();
        temaLabel = new javax.swing.JLabel();
        comboxtema = new com.alee.laf.combobox.WebComboBox();

        setMaximumSize(new java.awt.Dimension(463, 306));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        recommedPanel.setMaximumSize(new java.awt.Dimension(470, 117));
        recommedPanel.setOpaque(false);

        recommendTitlePanel.setOpaque(false);

        recommendTitleLabel.setText("Selecione um conte?do recomendado:");

        javax.swing.GroupLayout recommendTitlePanelLayout = new javax.swing.GroupLayout(recommendTitlePanel);
        recommendTitlePanel.setLayout(recommendTitlePanelLayout);
        recommendTitlePanelLayout.setHorizontalGroup(
            recommendTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommendTitlePanelLayout.createSequentialGroup()
                .addComponent(recommendTitleLabel)
                .addGap(0, 260, Short.MAX_VALUE))
        );
        recommendTitlePanelLayout.setVerticalGroup(
            recommendTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recommendTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        recommendScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        recommendContentPane.setLayout(new java.awt.FlowLayout(0));
        recommendScrollPane.setViewportView(recommendContentPane);

        javax.swing.GroupLayout recommedPanelLayout = new javax.swing.GroupLayout(recommedPanel);
        recommedPanel.setLayout(recommedPanelLayout);
        recommedPanelLayout.setHorizontalGroup(
            recommedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recommedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recommendScrollPane)
                    .addGroup(recommedPanelLayout.createSequentialGroup()
                        .addComponent(recommendTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        recommedPanelLayout.setVerticalGroup(
            recommedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recommendTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recommendScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(recommedPanel);

        choicePane.setMaximumSize(new java.awt.Dimension(470, 32767));
        choicePane.setOpaque(false);
        choicePane.setPreferredSize(new java.awt.Dimension(470, 192));

        choiceTitlePane.setOpaque(false);

        choiceLabel.setText("ou Escolha seu pr?prio conte?do:");

        javax.swing.GroupLayout choiceTitlePaneLayout = new javax.swing.GroupLayout(choiceTitlePane);
        choiceTitlePane.setLayout(choiceTitlePaneLayout);
        choiceTitlePaneLayout.setHorizontalGroup(
            choiceTitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choiceTitlePaneLayout.createSequentialGroup()
                .addComponent(choiceLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        choiceTitlePaneLayout.setVerticalGroup(
            choiceTitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choiceTitlePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choiceLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        choiceScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        selectablePane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        selectablePane.setMaximumSize(new java.awt.Dimension(440, 112));
        choiceScrollPane.setViewportView(selectablePane);

        paneFilter.setOpaque(false);
        paneFilter.setLayout(new java.awt.FlowLayout(0));

        tipoLabel.setText("Tipo");
        paneFilter.add(tipoLabel);

        comboxtipo.setBackground(new java.awt.Color(102, 255, 0));
        comboxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxtipoActionPerformed(evt);
            }
        });
        paneFilter.add(comboxtipo);

        nivellLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nivellLabel.setText("N?vel");
        paneFilter.add(nivellLabel);
        paneFilter.add(comboxnivel);

        dificuldadeLabel.setText("Dificuldade");
        paneFilter.add(dificuldadeLabel);
        paneFilter.add(comboxdificuldade);

        temaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        temaLabel.setText("Temas");
        paneFilter.add(temaLabel);
        paneFilter.add(comboxtema);

        javax.swing.GroupLayout choicePaneLayout = new javax.swing.GroupLayout(choicePane);
        choicePane.setLayout(choicePaneLayout);
        choicePaneLayout.setHorizontalGroup(
            choicePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, choicePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(choicePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(choiceTitlePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(choiceScrollPane))
                .addContainerGap())
        );
        choicePaneLayout.setVerticalGroup(
            choicePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choicePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choiceTitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(paneFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(choicePane);
    }// </editor-fold>//GEN-END:initComponents

    private void comboxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxtipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel choiceLabel;
    private javax.swing.JPanel choicePane;
    private javax.swing.JScrollPane choiceScrollPane;
    private javax.swing.JPanel choiceTitlePane;
    private com.alee.laf.combobox.WebComboBox comboxdificuldade;
    private com.alee.laf.combobox.WebComboBox comboxnivel;
    private com.alee.laf.combobox.WebComboBox comboxtema;
    private com.alee.laf.combobox.WebComboBox comboxtipo;
    private javax.swing.JLabel dificuldadeLabel;
    private javax.swing.JLabel nivellLabel;
    private javax.swing.JPanel paneFilter;
    private javax.swing.JPanel recommedPanel;
    private javax.swing.JPanel recommendContentPane;
    private javax.swing.JScrollPane recommendScrollPane;
    private javax.swing.JLabel recommendTitleLabel;
    private javax.swing.JPanel recommendTitlePanel;
    private javax.swing.JPanel selectablePane;
    private javax.swing.JLabel temaLabel;
    private javax.swing.JLabel tipoLabel;
    // End of variables declaration//GEN-END:variables

    
}
